import { User, Post } from './types';

export const mockUsers: Record<string, User> = {
  user1: {
    id: 'user1',
    name: 'أحمد محمد',
    username: '@ahmed_m',
    email: 'ahmed@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
    bio: 'مصور ومحتوى كريتور 📸',
    followersCount: 1250,
    followingCount: 340,
    postsCount: 45,
    isFollowing: false,
  },
  user2: {
    id: 'user2',
    name: 'فاطمة علي',
    username: '@fatima_ali',
    email: 'fatima@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
    bio: 'مصممة جرافيك | فنانة 🎨',
    followersCount: 2100,
    followingCount: 560,
    postsCount: 78,
    isFollowing: true,
  },
  user3: {
    id: 'user3',
    name: 'محمود حسن',
    username: '@mahmoud_h',
    email: 'mahmoud@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mahmoud',
    bio: 'مطور ويب | تقنية 💻',
    followersCount: 890,
    followingCount: 220,
    postsCount: 32,
    isFollowing: false,
  },
  currentUser: {
    id: 'current_user',
    name: 'أنت',
    username: '@your_username',
    email: 'you@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=You',
    bio: 'مستخدم صدى 🎵',
    followersCount: 450,
    followingCount: 320,
    postsCount: 28,
    isFollowing: false,
  },
};

export const mockPosts: Post[] = [
  {
    id: 'post1',
    userId: 'user1',
    user: mockUsers.user1,
    content: 'صباح الخير! يوم جديد مليء بالإمكانيات 🌅',
    image: 'https://images.unsplash.com/photo-1495567720989-cebdbdd97913?w=500&h=600&fit=crop',
    likesCount: 234,
    commentsCount: 45,
    sharesCount: 12,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'post2',
    userId: 'user2',
    user: mockUsers.user2,
    content: 'تصميم جديد انتهيت منه للتو! ما رأيكم؟ 🎨✨',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=600&fit=crop',
    likesCount: 567,
    commentsCount: 89,
    sharesCount: 34,
    isLiked: true,
    isSaved: true,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'post3',
    userId: 'user3',
    user: mockUsers.user3,
    content: 'نصيحة برمجية: استخدم async/await لكود أنظف وأسهل للقراءة 💡',
    likesCount: 345,
    commentsCount: 67,
    sharesCount: 23,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 'post4',
    userId: 'user1',
    user: mockUsers.user1,
    content: 'لحظات جميلة من رحلتي إلى الجبال 🏔️',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=600&fit=crop',
    likesCount: 456,
    commentsCount: 78,
    sharesCount: 45,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: 'post5',
    userId: 'user2',
    user: mockUsers.user2,
    content: 'الإبداع لا حدود له 🌟',
    image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=500&h=600&fit=crop',
    likesCount: 789,
    commentsCount: 123,
    sharesCount: 67,
    isLiked: true,
    isSaved: false,
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
  },
];
